---
title: "Think Tennessee Data Map"
subtitle: "`r params$county` County Fact Sheet"
format:
  ojo-report-template-html: default
# Formatting options -----------------------------------------------------------
logo: "www/thinktennessee-logo.png" # Other options are in the /www/ directory
number-sections: true
smooth-scroll: true
title-block-banner: "#1a884a" # The background color for the header banner
title-block-banner-color: "white" # The text color for the header banner
fontcolor: "black" # Default text color for the body
linkcolor: "#1a884a" # Default link color for the body
toc: false # This should be 'false' if your end goal is a PDF 
knitr: 
  opts_chunk: 
    fig.align: center # These are the default chunk options
    echo: false
    warning: false
    message: false
params:
  county: "Shelby"
# Remember that there are other formatting options in /_extensions/ojo-report-template/custom.scss
# You can also edit the header structure in /_extensions/ojo-report-template/title-block.html
# Document info ----------------------------------------------------------------
# author: Analyst
# date: last-modified
# description: |
#   This is where you can write a brief description of the publication if needed.
#   If you don't need it for your current project, you can just delete this parameter.
# abstract-title: "Executive Summary"
# abstract: |
#   This is where we'd write an abstract / executive summary. You can change the title
#   for this section by changing the `abstract-title` parameter, and you can 
#   delete the parameter if you don't need it.
---

```{r}

# To render to PDF after you've rendered your .html document:
# pagedown::chrome_print("./inst/county-summary-pdf/county-summary-pdf.html",
#                        "./inst/county-summary-pdf/county-summary-pdf.pdf", format = "pdf")

library(tidyverse)
library(ggthemes)
library(sf)
library(gt)
library(janitor)

# Data -------------------------------------------------------------------------
main_ds <- read_csv("./data/data-clean.csv")

census_ds <- tidycensus::get_acs(
  geography = "county",
  state = "TN",
  # county = params$county,
  year = 2022, 
  variables = c(
    #total
    total_population = "B01003_001",
    #race
    race_white = "B02001_002",
    race_black = "B02001_003",
    race_ai_an = "B02001_004",
    race_asian = "B02001_005",
    race_nh_pi = "B02001_006",
    race_other = "B02001_007",
    race_two_more = "B02001_007",
    race_two_more_inc = "B02001_009",
    race_two_more_exc = "B02001_010",
    #sex
    sex_m = "B01001_002",
    sex_f = "B01001_026",
    #other
    age_under_18 = "B09001_001"
  )) |>
  mutate(county = str_replace(NAME, " County, Tennessee", "")) |>
  select(-GEOID)

```

## `r params$county` County, Tennessee

:::: {.columns}

::: {.column width="60%"}

```{r county_map, fig.height=3}

county_shape <- read_rds("./data/tn-counties.rds") |>
  rename(county = NAME)
given_county_shape <- county_shape |>
  filter(county == params$county)

ggplot(county_shape) +
  # annotation_map_tile(zoom = 8, zoomin = -1) +
  geom_sf(fill = NA, color = "black") +
  geom_sf(data = given_county_shape, fill = "red", alpha = 0.5) +
  theme_map() 

```

:::

::: {.column width="30%"}

```{r county_census_stats} 
header_summary_stats <- main_ds |>
  filter(county == params$county) |>
  select(poverty_rate_all) |>
  pivot_longer(everything()) |>
  rename(variable = name,
         estimate = value)

census_ds |>
  filter(county == params$county) |>
  # inner_join(main_ds, by = "county") |>
  filter(variable %in% c("total_population")) |>
  select(variable, estimate) |>
  rbind(header_summary_stats) |>
  mutate(variable = make_clean_names(variable, case = "title")) |>
  gt(
    # caption = paste(params$county, "County")
  )

```

:::

::::

yadda yadad
